### ISSUE TITLE
organize repository

### ISSUE THREAD

**Issue by jennmcguire** [phys201/Hamiltonian-photonic-crystal#19]
You have many files with cryptic file names in your repository. You should use subdirectories to organize things like example data, tests and various inference files. You can also consider renaming files to make them more descriptive, which will also make your package easier to navigate and understand

**Comment by vnmanoharan** [comment]
Also you should delete any unused files, such as the `Deprecated_Inference_Methods` directory.  Git stores the entire history of all files, so if you need to, you can always access any earlier versions of files.  Keeping the repository clean and free of irrelevant files will help users and collaborators understand the package better.

**Comment by jennmcguire** [comment]
You should consider using directories to organize the files within your repo to make things easier to find

**Comment by thaodinh98** [comment]
I put subfolders into the photonic_hamiltonian folder to organize files: test codes are in test, data files are in data, and io.py, Model.py are in inference.
