### ISSUE TITLE
missing documentation.ipynb

### ISSUE THREAD

**Issue by jennmcguire** [phys201/Hamiltonian-photonic-crystal#2]
Your repository should contain a `documentation.ipynb` file where you import your package, describe your generative model, simulate data using your generative model and infer parameters from your simulated data. It should serve as an explanation of what you have done and how you did it, including both code and markdown cells with explanations of the code, theory and package

**Comment by fandusara** [comment]
We have updated the documentation.ipynb. Thanks for comment!
