### ISSUE TITLE
Try converting model to PyTensor

### ISSUE THREAD

**Issue by vnmanoharan** [phys201/Hamiltonian-photonic-crystal#25]
Try to convert your eigensolver to use PyTensor rather than numpy, so that automatic differentiation works.  It turns out that PyTensor does have an Op to calculate eigenvalues: `pytensor.tensor.nlinalg.Eig` and `pytensor.tensor.nlinalg.Eigh` (`Eigh` is for Hermitian matrices).  See here: https://www.pymc.io/projects/docs/en/latest/_modules/pytensor/tensor/nlinalg.html

Use this issue to keep track of progress and discuss any problems.

**Comment by thaodinh98** [comment]
I tried to do this in a new branch called tensorized-hamiltonian and new document called Document_trial. I converted Hamiltonian matrix into Pytensor and used pytensor.tensor.nlinalg.eig. Everything seems to be tensorized now but I got this error when trying to run it "'tensorvariable' object has no attribute 'rint' error".

**Comment by vnmanoharan** [comment]
Can you copy and paste the full backtrace?

**Comment by thaodinh98** [comment]
Yes, here it is

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'TensorVariable' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
File ~\anaconda\envs\phys201\Lib\site-packages\numpy\core\fromnumeric.py:57, in _wrapfunc(obj, method, *args, **kwds)
     56 try:
---> 57     return bound(*args, **kwds)
     58 except TypeError:
     59     # A TypeError occurs if the object does have such a method in its
     60     # class, but its signature is not identical to that of NumPy's. This
   (...)
     64     # Call _wrapit from within the except clause to ensure a potential
     65     # exception has a traceback chain.

TypeError: loop of ufunc does not support argument 0 of type TensorVariable which has no callable rint method

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: 'TensorVariable' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[6], line 22
     20 # Likelihood of observations
     21 pm.Potential("likelihood", logl(theta))
---> 22 idata_mh = pm.sample(500, tune=10)

File ~\anaconda\envs\phys201\Lib\site-packages\pymc\sampling\mcmc.py:481, in sample(draws, step, init, n_init, initvals, trace, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, keep_warning_stat, idata_kwargs, mp_ctx, **kwargs)
    479 # One final check that shapes and logps at the starting points are okay.
    480 for ip in initial_points:
--> 481     model.check_start_vals(ip)
    482     _check_start_shape(model, ip)
    484 sample_args = {
    485     "draws": draws,
    486     "step": step,
   (...)
    495     "discard_tuned_samples": discard_tuned_samples,
    496 }

File ~\anaconda\envs\phys201\Lib\site-packages\pymc\model.py:1765, in Model.check_start_vals(self, start)
   1759     valid_keys = ", ".join(value_names_set)
   1760     raise KeyError(
   1761         "Some start parameters do not appear in the model!\n"
   1762         f"Valid keys are: {valid_keys}, but {extra_keys} was supplied"
   1763     )
-> 1765 initial_eval = self.point_logps(point=elem)
   1767 if not all(np.isfinite(v) for v in initial_eval.values()):
   1768     raise SamplingError(
   1769         "Initial evaluation of model at starting point failed!\n"
   1770         f"Starting values:\n{elem}\n\n"
   1771         f"Initial evaluation results:\n{initial_eval}"
   1772     )

File ~\anaconda\envs\phys201\Lib\site-packages\pymc\model.py:1795, in Model.point_logps(self, point, round_vals)
   1793 factors = self.basic_RVs + self.potentials
   1794 factor_logps_fn = [at.sum(factor) for factor in self.logp(factors, sum=False)]
-> 1795 return {
   1796     factor.name: np.round(np.asarray(factor_logp), round_vals)
   1797     for factor, factor_logp in zip(
   1798         factors,
   1799         self.compile_fn(factor_logps_fn)(point),
   1800     )
   1801 }

File ~\anaconda\envs\phys201\Lib\site-packages\pymc\model.py:1796, in <dictcomp>(.0)
   1793 factors = self.basic_RVs + self.potentials
   1794 factor_logps_fn = [at.sum(factor) for factor in self.logp(factors, sum=False)]
   1795 return {
-> 1796     factor.name: np.round(np.asarray(factor_logp), round_vals)
   1797     for factor, factor_logp in zip(
   1798         factors,
   1799         self.compile_fn(factor_logps_fn)(point),
   1800     )
   1801 }

File <__array_function__ internals>:200, in round_(*args, **kwargs)

File ~\anaconda\envs\phys201\Lib\site-packages\numpy\core\fromnumeric.py:3763, in round_(a, decimals, out)
   3754 @array_function_dispatch(_around_dispatcher)
   3755 def round_(a, decimals=0, out=None):
   3756     """
   3757     Round an array to the given number of decimals.
   3758 
   (...)
   3761     around : equivalent function; see for details.
   3762     """
-> 3763     return around(a, decimals=decimals, out=out)

File <__array_function__ internals>:200, in around(*args, **kwargs)

File ~\anaconda\envs\phys201\Lib\site-packages\numpy\core\fromnumeric.py:3337, in around(a, decimals, out)
   3245 @array_function_dispatch(_around_dispatcher)
   3246 def around(a, decimals=0, out=None):
   3247     """
   3248     Evenly round to the given number of decimals.
   3249 
   (...)
   3335 
   3336     """
-> 3337     return _wrapfunc(a, 'round', decimals=decimals, out=out)

File ~\anaconda\envs\phys201\Lib\site-packages\numpy\core\fromnumeric.py:66, in _wrapfunc(obj, method, *args, **kwds)
     57     return bound(*args, **kwds)
     58 except TypeError:
     59     # A TypeError occurs if the object does have such a method in its
     60     # class, but its signature is not identical to that of NumPy's. This
   (...)
     64     # Call _wrapit from within the except clause to ensure a potential
     65     # exception has a traceback chain.
---> 66     return _wrapit(obj, method, *args, **kwds)

File ~\anaconda\envs\phys201\Lib\site-packages\numpy\core\fromnumeric.py:43, in _wrapit(obj, method, *args, **kwds)
     41 except AttributeError:
     42     wrap = None
---> 43 result = getattr(asarray(obj), method)(*args, **kwds)
     44 if wrap:
     45     if not isinstance(result, mu.ndarray):

TypeError: loop of ufunc does not support argument 0 of type TensorVariable which has no callable rint method

**Comment by vnmanoharan** [comment]
With the tensorized likelihood function, you no longer need the `LogLike` Op.  You can instead just use the likelihood function directly:
```
pm.Potential("likelihood", likelihood(theta, y, normf, noisey))
```
If you do this you'll see that there's a problem with how you're defining the matrix in terms of tensor variables.

**Comment by vnmanoharan** [comment]
The model shown below will compile and sample, though I get lots of divergences.
<details><summary>Details</summary>
<p>

```python
def likelihood(theta, y, x, sigma_y):
    """
    returns the loglike likelihood of our model
        
    Parameters:
        theta: the parameters in Hamiltonian matrix (list)
        y, x, sigma_y: our data (numpy arrays)
        
    Return:
        the loglike likelihood (float)
    """
    #for our four-basis Hamiltonian, the parameters include
    #interaction-between-modes terms h11, u20;
    #background A0 and heights of 4 peaks A1, A2, A3, A4
    #peak width (assumed to be the same for all peaks) sigma_L
    h11, u20, A0, A1, A2, A3, A4, sigma_L = theta
    
    #energy of each mode is assumed to be fixed
    e = 0.6346    # for k = (0.05,0) the eigen frequency of uncoupled slab mode 1 (*2 degeneracy)
    e2 = 0.669    # for k = (0.05,0) the eigen frequency of uncoupled slab mode 2 (*2 degeneracy)

    #Hamiltonian matrix
    ham_np = np.array([[e2,h11,u20,h11],
                       [h11,e,h11,u20],
                       [u20,h11,e,h11],
                       [h11,u20,h11,e2]])
    ham = pytensor.shared(np.zeros((4,4)))
    for row in range(4):
        for col in range(4):
            ham = pt.set_subtensor(ham[row, col], ham_np[row, col])
    
    #peak heights and peak positions
    An_np = np.array([A1,A2,A3,A4])
    An = pytensor.shared(np.zeros(4))
    for col in range(4):
        An = pt.set_subtensor(An[col], An_np[col])

    Cn = pt.nlinalg.eigh(ham)[0]

    #expectation value as sum of 4 gaussian peaks and background
    #gaussian_list = [Ai * pt.exp(-pt.sqr(x - Ci) / (2 * pt.sqr(sigma_L))) for Ai, Ci in zip(An, Cn)]
    #line = A0 + pt.sum(gaussian_list,axis=0)
    line = A0 + An[0] * pt.exp(-pt.sqr(x - Cn[0]) / (2 * pt.sqr(sigma_L))) + An[1] * pt.exp(-pt.sqr(x - Cn[1]) / (2 * pt.sqr(sigma_L))) + An[2] * pt.exp(-pt.sqr(x - Cn[2]) / (2 * pt.sqr(sigma_L))) + An[3] * pt.exp(-pt.sqr(x - Cn[3]) / (2 * pt.sqr(sigma_L)))
    return pt.sum(-(0.5 / pt.sqr(sigma_y)) * pt.sqr(y - line))

ham_model = pm.Model()
with ham_model:
    # Priors for unknown model parameters    , transform = None  h11, A0, A1, sigma_L = theta
    A0 = pm.Uniform('background',lower=0,upper=1.2)
    A1 = pm.Uniform("A1", lower=0.5, upper=2.5)
    A2 = pm.Uniform("A2", lower=0.5, upper=2.5)
    A3 = pm.Uniform("A3", lower=0.5, upper=2.5)
    A4 = pm.Uniform("A4", lower=0.5, upper=2.5)
    h11 = pm.Uniform('h11',lower=0.003,upper=0.01)
    u20 = pm.Uniform('u20',lower=-1e-3,upper=1e-3)
    # neff = pm.Uniform('neff',2,2.2)         # ignore this for now
    # ratio = pm.Uniform('ratio',0.2,0.4)     # ignore this for now
    sigma_L = pm.Uniform('peak_width',lower=0.0005,upper=0.01)
    
    # likelihood
    theta = pt.as_tensor_variable([h11,u20, A0, A1,A2,A3,A4, sigma_L])
    
    # Likelihood of observations
    pm.Potential("likelihood", likelihood(theta, y, normf, noisey))
    idata = pm.sample(500)
```




</p>
</details>

**Comment by vnmanoharan** [comment]
Fixed now -- see pull request for a working implementation.  The problem was that you were using the actual noise values of the simulated data as the standard deviation in your likelihood function.  Make sure you use the standard deviation of the noise instead.

**Comment by thaodinh98** [comment]
Thank you so much, Vinny. I was able to use your suggestions to update the model.py. And everything in documentation notebook now runs well with NUTS without divergences.
