### ISSUE TITLE
consider moving functions into a .py file

### ISSUE THREAD

**Issue by erandichavez** [phys201/Hamiltonian-photonic-crystal#29]
Consider the functions and classes in your documentation notebook (ham2, my_gausslike, Peak_Position, etc...) into a .py file in your package and then load them in. This will save space and make your documentation notebook more readable.

**Comment by thaodinh98** [comment]
We did move all of these into the Model.py. Probably we didn't clearly say where we used it in the notebook, we will rewrite the documentation notebook to make it clearer.
