### ISSUE TITLE
missing docstrings

### ISSUE THREAD

**Issue by jennmcguire** [phys201/Hamiltonian-photonic-crystal#3]
All functions, classes and methods should have docstrings describing what they are and what they do. None of the functions in `Inference ver 2_Pytensor method.ipynb` and `Inference ver 1_randomdraw.ipynb` contain docstrings

**Comment by jennmcguire** [comment]
Missing docstrings in `io.py`

**Comment by fandusara** [comment]
we updated io_data.py (because duplicate name problem, io.py just causes some error on my local)
